blank_issues_enabled: false
contact_links:
  - name: 📋 View Organization Project Board
    url: https://github.com/orgs/YOUR_ORG_NAME/projects/YOUR_PROJECT_NUMBER
    about: View all issues across our 3 repositories in the unified project board
  - name: 🔄 Create Issue in Frontend Repo
    url: https://github.com/YOUR_ORG_NAME/frontend-repo/issues/new/choose
    about: Create an issue for the frontend repository
  - name: 📱 Create Issue in Mobile Repo
    url: https://github.com/YOUR_ORG_NAME/mobile-repo/issues/new/choose
    about: Create an issue for the mobile repository
