blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/orgs/closure/discussions
    about: Check our documentation and community discussions for common questions
