name: Deploy Staging Environment

on:
  push:
    branches:
      - staging
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: none
      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli
      - name: Install Project Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Create storage directories
        run: |
          mkdir -p storage/testing
          mkdir -p storage/logs
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
      - name: Set up environment file
    #   @TODO convert this to Actions env vars, remove unused env vars
        run: |
          cp .env.example .env || echo "APP_NAME=\"Closure API\"
          APP_ENV=testing
          APP_DEBUG=false
          APP_TIMEZONE=UTC
          APP_URL=http://localhost
          
          APP_LOCALE=en
          APP_FALLBACK_LOCALE=en
          APP_FAKER_LOCALE=en_US
          
          APP_MAINTENANCE_DRIVER=file
          BCRYPT_ROUNDS=4
          
          LOG_CHANNEL=stack
          LOG_STACK=single
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=error
          
          # Database Configuration (Testing uses SQLite)
          DB_CONNECTION=tenant_test
          DB_DATABASE=:memory:
          DB_LANDLORD_DATABASE=landlord_test
          DB_TENANT_DATABASE=tenant_test
          
          # Audit Database (Testing)
          AUDIT_DB_CONNECTION=audit_test
          AUDIT_DB_DATABASE=:memory:
          
          # Cache Configuration
          CACHE_STORE=array
          CACHE_PREFIX=
          
          # Session Configuration
          SESSION_DRIVER=array
          SESSION_LIFETIME=120
          SESSION_ENCRYPT=false
          
          # Queue Configuration
          QUEUE_CONNECTION=sync
          
          # Mail Configuration
          MAIL_MAILER=array
          MAIL_FROM_ADDRESS=test@example.com
          MAIL_FROM_NAME=\"\${APP_NAME}\"
          
          # Filesystem Configuration
          FILESYSTEM_DISK=local
          
          # Laravel Sanctum
          SANCTUM_STATEFUL_DOMAINS=localhost
          SANCTUM_GUARD=web
          SANCTUM_TOKEN_EXPIRY_MINUTES=15
          SANCTUM_REFRESH_TOKEN_EXPIRY_DAYS=30
          
          # Multitenancy Configuration
          MULTITENANCY_TENANT_FINDER=token-based
          
          # API Configuration
          API_VERSION=v1
          API_RATE_LIMIT=60
          
          # Development/Testing Settings
          TELESCOPE_ENABLED=false
          PULSE_ENABLED=false
          NIGHTWATCH_ENABLED=false
          DEBUGBAR_ENABLED=false
          SCRAMBLE_ENABLED=false
          
          # Disable external services for testing
          SENTRY_LARAVEL_DSN=
          SENTRY_TRACES_SAMPLE_RATE=0.0" > .env
      - name: Set app key
        run: php artisan key:generate --force
      - name: Run static analysis
        run: composer run analyse
      # - name: Run tests
      #   run: php artisan test --bail
      - name: Deploy Environment
        run: vapor deploy staging --commit="${GITHUB_SHA}" --message="${GITHUB_MESSAGE}" --without-waiting
    env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
        